### ISSUE TITLE
Minor Bug: Documentation on https://www.claudiokuenzler.com/monitoring-plugins/check_lxc.php 

### ISSUE THREAD

**Issue by wlma** [Napsty/check_lxc#3]
Requirements Memory, Command wrong
"cat /etc/cgroups | grep memory"

should imho be:
'cat /proc/cgroups | grep memory' 

(i'm running a debian-based system, maybe it's different on other distributions )

**Comment by Napsty** [comment]
Yep, looks like I was thinking one thing and typing another.  Thx!

**Comment by Napsty** [comment]
Fixed on https://www.claudiokuenzler.com/monitoring-plugins/check_lxc.php. Sorry, I forgot about that issue.
