### ISSUE TITLE
Syntax error: operand expected

### ISSUE THREAD

**Issue by wopfel** [Napsty/check_lxc#8]
Hi, I'm running check_lxc on a Proxmox server. I haven't updated the system for some time. But I've updated the Proxmox server today and since then, check_lxc fails:

```
# LANG=C /usr/local/bin/check_lxc -n 509 -t mem
/usr/local/bin/check_lxc: line 157: 0 * 100 / : syntax error: operand expected (error token is "/ ")
```

Lines 156 and 157 are:

```
        limit=$(lxc-cgroup -n ${container} memory.limit_in_bytes)
        used_perc=$(( $used * 100 / $limit))
```

Unfortunately, lxc-cgroup is returning no result. So this is the reason why check_lxc fails. 

But I don't have a clue so far what's wrong with the lxc-cgroup command...

Kind regards,
Bernd

**Comment by Napsty** [comment]
What LXC version is this? 
Can you run `lxc-checkconfig` to see if something is missing?

**Comment by wopfel** [comment]
Version of LXC according to `apt list`:
> lxc-pve/stable,now 3.0.2+pve1-2 amd64 [installed,auto-removable]
> lxcfs/stable,now 3.0.0-1 amd64 [installed,upgradable to: 3.0.2-2]

Output of `lxc-cgroup --version`
> 3.0.2

Output of `lxc-checkconfig`:
> Kernel configuration not found at /proc/config.gz; searching...
> Kernel configuration found at /boot/config-4.15.17-3-pve
> --- Namespaces ---
> Namespaces: enabled
> Utsname namespace: enabled
> Ipc namespace: enabled
> Pid namespace: enabled
> User namespace: enabled
> Network namespace: enabled
> 
> --- Control groups ---
> Cgroups: enabled
> 
> Cgroup v1 mount points:
> /sys/fs/cgroup/systemd
> /sys/fs/cgroup/rdma
> /sys/fs/cgroup/devices
> /sys/fs/cgroup/net_cls,net_prio
> /sys/fs/cgroup/cpu,cpuacct
> /sys/fs/cgroup/perf_event
> /sys/fs/cgroup/blkio
> /sys/fs/cgroup/cpuset
> /sys/fs/cgroup/memory
> /sys/fs/cgroup/freezer
> /sys/fs/cgroup/hugetlb
> /sys/fs/cgroup/pids
> 
> Cgroup v2 mount points:
> 
> 
> Cgroup v1 clone_children flag: enabled
> Cgroup device: enabled
> Cgroup sched: enabled
> Cgroup cpu account: enabled
> Cgroup memory controller: enabled
> Cgroup cpuset: enabled
> 
> --- Misc ---
> Veth pair device: enabled, loaded
> Macvlan: enabled, not loaded
> Vlan: enabled, not loaded
> Bridges: enabled, not loaded
> Advanced netfilter: enabled, not loaded
> CONFIG_NF_NAT_IPV4: enabled, not loaded
> CONFIG_NF_NAT_IPV6: enabled, not loaded
> CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
> CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
> CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, not loaded
> CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
> FUSE (for use with lxcfs): enabled, not loaded
> 
> --- Checkpoint/Restore ---
> checkpoint restore: enabled
> CONFIG_FHANDLE: enabled
> CONFIG_EVENTFD: enabled
> CONFIG_EPOLL: enabled
> CONFIG_UNIX_DIAG: enabled
> CONFIG_INET_DIAG: enabled
> CONFIG_PACKET_DIAG: enabled
> CONFIG_NETLINK_DIAG: enabled
> File capabilities:
> 
> Note : Before booting a new kernel, you can check its configuration
> usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig

There are updates available on the proxmox host. Maybe the issue is resolved then. I'll try...

**Comment by Napsty** [comment]
I just remembered there was somewhere a new Ubuntu 18.04 with LXC 3.x around. 

```
# dpkg -l|grep lxc
ii  liblxc-common                         3.0.1-0ubuntu1~18.04.1            amd64        Linux Containers userspace tools (common tools)
ii  liblxc1                               3.0.1-0ubuntu1~18.04.1            amd64        Linux Containers userspace tools (library)
ii  lxc                                   3.0.1-0ubuntu1~18.04.1            all          Transitional package - lxc -> lxc-utils
ii  lxc-utils                             3.0.1-0ubuntu1~18.04.1            amd64        Linux Containers userspace tools
ii  lxcfs                                 3.0.1-0ubuntu2~18.04.1            amd64        FUSE based filesystem for LXC
```


Just tested it, lxc-cgroup still allows the old way (using -n parameter), too:

```
# lxc-cgroup container memory.limit_in_bytes
9223372036854771712

# lxc-cgroup -n container memory.limit_in_bytes
9223372036854771712
```

So the plugin works with LXC 3.x, too:

```
# /usr/lib/nagios/plugins/check_lxc.sh -n container -t mem
LXC container OK - Used Memory: 1345 MB|mem=1411010560B;0;0;0;0
```

There must be something else on your machine that the lxc-cgroup command is not showing any info.

**Comment by wopfel** [comment]
Meanwhile, I've updated the proxmox host. But the results didn't change.

Thanks for trying skipping the -n switch. Same here, there's no difference using -n or skipping it. Even further, I can call the command with a non-existing container like `lxc-cgroup bla blabla` and there's no output shown (even no error).

On the host though, there's some output when using the filesystem: 
```
# cat /sys/fs/cgroup/memory/lxc/509/memory.limit_in_bytes`
536870912
```

Having this, I've updated your script so that it works on my host:
```
        used=$(cat /sys/fs/cgroup/memory/lxc/${container}/memory.usage_in_bytes)
        limit=$(cat /sys/fs/cgroup/memory/lxc/${container}/memory.limit_in_bytes)
```

```
# /usr/local/bin/check_lxc -n 509 -t mem
LXC 509 OK - Used Memory: 168 MB|mem=176558080B;0;0;0;0
# /usr/local/bin/check_lxc -n 509 -t mem -c 2 -w 1
LXC 509 CRITICAL - Used Memory: 32% (168 MB)|mem=176672768B;5368709;10737418;0;536870912
```

Just for info: my `pveversion` is: `pve-manager/5.2-9/4b30e8f9 (running kernel: 4.15.17-3-pve)`

@Napsty thank you very much for your time and your comments. I'm closing this issue now, as lxc-cgroup is working for you and the problems seem to be related to my machine. Sorry for bothering...
