### ISSUE TITLE
Syntax Error after Upgrade

### ISSUE THREAD

**Issue by pjweder** [Napsty/check_lxc#9]
OS: Ubuntu 18.04.1 LTS
LXC: 3.0.2

Check doesn't work since the last updates:

Error:
/usr/lib/nagios/plugins/check_lxc.sh: line 253: +  : syntax error: operand expected (error token is "+  ")

**Comment by Napsty** [comment]
Thanks for reporting. This is caused by https://github.com/lxc/lxc/issues/2742. 
I will add a sanity check in the plugin though.

**Comment by Napsty** [comment]
Fixed in 0.6.2
